### ISSUE TITLE
After following everything and downloading the model, this appeared

### ISSUE THREAD

**Issue by HASAN3DG** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#1]
hi 
After following everything and downloading the model, this appeared
![Screenshot 2023-11-23 182630](https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion/assets/74836845/68faf898-ba10-425f-bcf9-3ca8f1f9776a)

**Comment by thecooltechguy** [comment]
Hi! Just to make sure, have you restarted ComfyUI? and in the startup logs for ComfyUI, does it say "IMPORT FAILED" for this module, or does it import properly?

thanks!

**Comment by HASAN3DG** [comment]
thanks man 
look 
[
![Screenshot 2023-11-23 215542](https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion/assets/74836845/11a3c619-c7a8-49eb-b72d-a9195e6d8d1a)
](url)

**Comment by thecooltechguy** [comment]
Hi @HASAN3DG! Can you try pulling the latest version of this module and re-installing from the requirements.txt file to see if it works? I just made some changes to simplify installation & make it work in more environments. thanks!

**Comment by klinter007** [comment]
after downloading the models and placing them in the folder, restarting both terminal and web tab solved this for me.

**Comment by HASAN3DG** [comment]
Thanks guys Now it works well

**Comment by thecooltechguy** [comment]
Sweet!
