### ISSUE TITLE
SVD Model Loader node fails to load

### ISSUE THREAD

**Issue by alessandroperilli** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#2]
ComfyUI import the custom node suite just fine, but the `SVD Model Loader` node fails to appear in the menu due to the following error:

> [ERROR] An error occurred while retrieving information for the 'SVDModelLoader' node.
> Traceback (most recent call last):
>   File "xyz/ComfyUI/server.py", line 418, in get_object_info
>     out[x] = node_info(x)
>              ^^^^^^^^^^^^
>   File "xyz/ComfyUI/server.py", line 396, in node_info
>     info['input'] = obj_class.INPUT_TYPES()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/ComfyUI-Stable-Video-Diffusion/nodes.py", line 28, in INPUT_TYPES
>     "default" : checkpoints[0],
>                 ~~~~~~~~~~~^^^
> IndexError: list index out of range

Thank you

**UPDATE**

I figured it out: the error (and the node loading failure) occurs if ComfyUI is started before the models are placed in the indicated folders.

**Comment by thecooltechguy** [comment]
Ah yup, I think I should make this clearer in the README. sorry about that!
