### ISSUE TITLE
I I have downloaded，but  red

### ISSUE THREAD

**Issue by ErisenYeh** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#21]
When loading the graph, the following node types were not found:
SVDDecoder
SVDModelLoader
SVDSampler
Nodes that have failed to load will show as red on the graph.

**Comment by FrankAnger** [comment]
You have to download models mentioned in README in ComfyUI\models\svd
It will not install properly without them

Here is an issue where this got figured out https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion/issues/13

**Comment by ErisenYeh** [comment]
grateful
