### ISSUE TITLE
Getting an OOM on decode

### ISSUE THREAD

**Issue by Mindspherical** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#3]
Thanks for creating this node so quickly!

I'm running on an A100 with 40gb VRAM, but seeing this:

<img width="745" alt="image" src="https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion/assets/117719106/e6193b98-2de6-4931-9bd1-c688678f493a">

This is with normal SVD. SVD_xt would OOM before even running inference.

**Comment by Mindspherical** [comment]
Fixed this by lowering the t_value of the decoder to 1.

**Comment by thecooltechguy** [comment]
got it, thank you!
