### ISSUE TITLE
i dont find video combine graph

### ISSUE THREAD

**Issue by D-Mad** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#4]
![image](https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion/assets/8207507/5b08ae41-866c-4693-952e-b4b07ce50ec2)

**Comment by thecooltechguy** [comment]
Hi! The VideoCombine node is provided by this custom node: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
